### ISSUE TITLE
Continued support for C++

### ISSUE THREAD

**Issue by rleigh-codelibre** [ome/ome-model#104]
The ome-model repository still contains all of the code generation infrastructure and templates as well as source code for C++.  Do you want to retain it here, given that it's currently untested, or are you happy for it to live over in https://gitlab.com/codelibre/ome/ome-model where it's actively tested on multiple platforms?

If you don't want it here, because any changes which affect the C++ code or templates can't be effectively tested, I'll be happy to make a PR which removes the templates and/or the code.

**Comment by sbesson** [comment]
See also https://github.com/ome/ome-model/pull/108#pullrequestreview-376920254

**Comment by rleigh-codelibre** [comment]
@sbesson I'll follow up here rather than on #108 where it's a little off-topic.

If you want to go ahead with the removal, I can do this as a followup to #108 after it is merged.  So the point after #108 is merged would be the last version where the C++ implementation would directly match the Java implementation and would be known to be fully functional (with my separate GitLab testing of the PR).  After that it can be dropped in its entirety including code, templates and xsd-fu support.

There is nothing specifically to extract from the OME ome-model repository, because the GitLab fork contains all of the code which would be dropped, and will continue to retain and test that code.  As such, if you ever want to reintroduce the code again at a later date, it will be there to pick back up.

**Comment by sbesson** [comment]
Closing as per #111
