### ISSUE TITLE
Python 3.9 requires Genshi update

### ISSUE THREAD

**Issue by rleigh-codelibre** [ome/ome-model#126]
Due to changes in the language, the vendored Genshi dependency will require an update.  Support is currently being developed upstream, and a new release is expected reasonably soon.

**Comment by rleigh-codelibre** [comment]
I've got generation working with Python 3.9 in [this merge request and pipeline](https://gitlab.com/rleigh/ome-model/-/pipelines/214929507).  No code generation differences.

A few issues found with Genshi which have been [pushed upstream](https://github.com/edgewall/genshi/pull/35).  That's still being investigated and reviewed.

Depending upon how urgently you want Python 3.9 support, I could open a pull request with the ome-model updates I tested and merged on GitLab.  Or you can wait until the fixes are merged upstream and then take the new upstream Genshi.

**Comment by sbesson** [comment]
Hi @rleigh-codelibre, thanks for the heads-up and all the preliminary work on the Python compatibility of Genshi.

From our side, there is no driver or urgent need to support Python 3.9 at the moment. If the expectations is that the changes should make it into an upstream Genshi release, our preference would be to consume the official package and drop the patched Genshi copy in this repository by the same occasion. We will track the progress of your contribution to the Genshi repository and we can revisit this in a few months if necessary

**Comment by rleigh-codelibre** [comment]
OK.  Do bear in mind that the reason we aren't using the upstream directly is because it has historically been subject to frequent breakage, otherwise we would just have installed it directly with pip.  And as you can see, Python 3.9 is not an exception to this rule!  So you may still want to include it directly to avoid random breakage.  Hopefully there will be a tagged release which will be usable for ome-model sometime soon, and that will likely be the optimal point to pick up a fresh copy.
