### ISSUE TITLE
Wrong API Documentation link

### ISSUE THREAD

**Issue by Silver-Fang** [ome/ome-model#152]
On [this page](https://docs.openmicroscopy.org/ome-model/6.2.2/ome-xml/java-library.html), the link [online API documentation](https://downloads.openmicroscopy.org/latest/bio-formats/api/) refers to a wrong BioFormats page, which does not contain ome.xml.* packages as described in the page.

**Comment by sbesson** [comment]
Thanks @Silver-Fang, it's an oversight indeed as the sources, the artifacts and the API documentation of this component are now completely separated from Bio-Formats. I have opened a [Pull Request](https://github.com/ome/ome-model/pull/153) to update the links accordingly
